import Head from 'next/head'
import React from 'react'
import styled from 'styled-components'
import { GlobalHeader } from './header/GlobalHeader'

const Layout: React.FC<{ children: React.ReactNode }> = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <GlobalHeader />
        <MainContents>{children}</MainContents>
      </main>
    </>
  )
}
export default Layout

const MainContents = styled.div`
  margin: 16px auto;
  width: 90vw;
  max-width: 900px;

  h2 {
    color: #3e4f6d;
    font-size: 2em;
  }
`
