version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nginx
    environment:
      CLIENT_MAX_BODY_SIZE: 20M

  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - stella-finder-ui
      - stella-finder-server

  stella-finder-ui:
    image: node:14.17.3-alpine
    container_name: stella-finder-ui
    hostname: stella-finder-ui
    volumes:
      - "./ui/:/src"
    working_dir: /src
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - stella-finder-db

  stella-finder-server:
    image: golang:latest
    container_name: stella-finder-server
    hostname: stella-finder-server
    volumes:
      - "./server/:/go"
    working_dir: /go
    environment:
      - GO111MODULE=on
      - GOPATH= # GOPATHクリア
    tty: true
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - stella-finder-ui
    depends_on:
      - stella-finder-db

  stella-finder-db:
    image: mysql:8.0
    container_name: stella-finder-db
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: "redis:latest"
    container_name: stella-finder-session-db
    tty: true
    expose:
      - "6379"
