version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - hoshi-atsume-ui
      - hoshi-atsume-server

  hoshi-atsume-ui:
    image: node:14.17.3-alpine
    container_name: hoshi-atsume-ui
    hostname: hoshi-atsume-ui
    volumes:
      - "./ui/:/src"
    working_dir: /src
    command: [sh, -c, yarn install && yarn dev]
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hoshi-atsume-db

  hoshi-atsume-server:
    image: golang:latest
    container_name: hoshi-atsume-server
    hostname: hoshi-atsume-server
    volumes:
      - "./server/:/go"
    working_dir: /go
    environment:
      - GO111MODULE=on
      - GOPATH= # GOPATHクリア
    command: [sh, -c, go mod download && go run src/main.go]
    tty: true
    ports:
      - "3001:3001"
    links:
      - hoshi-atsume-ui
    depends_on:
      - hoshi-atsume-db

  hoshi-atsume-db:
    image: mysql:8.0
    container_name: hoshi-atsume-db
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: "redis:latest"
    tty: true
    expose:
      - "6379"
