version: '3'
services:
  https-portal:
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://nginx:8080'

  stella-finder-ui:
    command: [ sh, -c, yarn install && yarn dev ]

  stella-finder-server:
    command: [ sh, -c, go mod download && go run src/main.go ]