// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package moon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoonApiClient is the client API for MoonApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoonApiClient interface {
	MoonInfo(ctx context.Context, in *MoonInfoRequest, opts ...grpc.CallOption) (*MoonInfoResponse, error)
}

type moonApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMoonApiClient(cc grpc.ClientConnInterface) MoonApiClient {
	return &moonApiClient{cc}
}

func (c *moonApiClient) MoonInfo(ctx context.Context, in *MoonInfoRequest, opts ...grpc.CallOption) (*MoonInfoResponse, error) {
	out := new(MoonInfoResponse)
	err := c.cc.Invoke(ctx, "/moon.MoonApi/MoonInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoonApiServer is the server API for MoonApi service.
// All implementations must embed UnimplementedMoonApiServer
// for forward compatibility
type MoonApiServer interface {
	MoonInfo(context.Context, *MoonInfoRequest) (*MoonInfoResponse, error)
	mustEmbedUnimplementedMoonApiServer()
}

// UnimplementedMoonApiServer must be embedded to have forward compatible implementations.
type UnimplementedMoonApiServer struct {
}

func (UnimplementedMoonApiServer) MoonInfo(context.Context, *MoonInfoRequest) (*MoonInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoonInfo not implemented")
}
func (UnimplementedMoonApiServer) mustEmbedUnimplementedMoonApiServer() {}

// UnsafeMoonApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoonApiServer will
// result in compilation errors.
type UnsafeMoonApiServer interface {
	mustEmbedUnimplementedMoonApiServer()
}

func RegisterMoonApiServer(s grpc.ServiceRegistrar, srv MoonApiServer) {
	s.RegisterService(&MoonApi_ServiceDesc, srv)
}

func _MoonApi_MoonInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoonInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoonApiServer).MoonInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moon.MoonApi/MoonInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoonApiServer).MoonInfo(ctx, req.(*MoonInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoonApi_ServiceDesc is the grpc.ServiceDesc for MoonApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoonApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moon.MoonApi",
	HandlerType: (*MoonApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MoonInfo",
			Handler:    _MoonApi_MoonInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/hoshiyomi/moon.proto",
}
