import Head from "next/head";

export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <>
            <Head>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>{children}</main>
        </>
    )
}