name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Pull
        run: cd ${{ secrets.DEPLOY_DIR }} && git pull
      - name: Migrate DB
        run: cd ${{ secrets.DEPLOY_DIR }} && ./scripts/prod/migrate-db.sh
      - name: Stop server
        run: cd ${{ secrets.DEPLOY_DIR }} && ./scripts/prod/docker-compose-wrapper.sh down
      - name: Start server
        run: cd ${{ secrets.DEPLOY_DIR }} && ./scripts/prod/docker-compose-wrapper.sh up -d
