name: deploy

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: [stella-finder]
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/prod/socker-compose-wrapper down
      - run: ./scripts/prod/socker-compose-wrapper up
