name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Pull
        run: cd ${{ secrets.DEPLOY_DIR }} && git pull
      - name: Restart server
        run: cd ${{ secrets.DEPLOY_DIR }} && ./scripts/prod/docker-compose-wrapper.sh down && ./scripts/prod/docker-compose-wrapper.sh up -d
