name: Update Licenses

on: pull_request

jobs:
  update-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install licensed
        run: gem install licensed -v '~> 3.0'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install python dependencies
        run: pip install PyYAML
      - name: yarn install
        run: (cd ui/ && yarn install)
      - name: Check licenses diff
        run: licensed cache && diff ui/public/licenses.txt <(python scripts/ci/make-license-list.py)
